version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: my-laravel-app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - ./opcache.ini:/usr/local/etc/php/conf.d/opcache.ini
        environment:
            - APP_ENV=local
            - DB_HOST=db
            - DB_PORT=3306
            - DB_DATABASE=${DB_DATABASE}
            - DB_USERNAME=${DB_USERNAME}
            - DB_PASSWORD=${DB_PASSWORD}
        networks:
            - app-network
        expose:
            - "9000"
        depends_on:
            - db

    nginx:
        image: nginx:latest
        container_name: my-nginx
        restart: unless-stopped
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./:/var/www
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./certbot/conf:/etc/letsencrypt
            - ./certbot/www:/var/www/certbot
        depends_on:
            - app
        networks:
            - app-network

    db:
        image: mysql:8.0
        container_name: my-mysql
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - app-network
        ports:
            - "3306:3306"
    redis:
        image: redis:alpine
        container_name: my-redis
        networks:
            - app-network
        ports:
            - "6379:6379"

    certbot:
        image: certbot/certbot
        container_name: certbot
        volumes:
            - ./certbot/conf:/etc/letsencrypt
            - ./certbot/www:/var/www/certbot
        entrypoint: "/bin/sh -c 'trap exit TERM; while :; do sleep 1; done;'"
networks:
    app-network:
        driver: bridge

volumes:
    dbdata:
        driver: local
